### ISSUE TITLE
How can this be used in projects that do not have browserify to "require"?

### ISSUE THREAD

**Issue by tgelu** [samcal/angular-elm-components#1]

**Comment by amitaibu** [comment]
@samcal thank you for this useful package!

@tgelu What I've done is in `index.html` after loading the Angular app, I'm loading the Elm app:

```html
    <script src="scripts/app.js"></script>

    <!-- The Elm app. -->
    <script type="text/javascript" src="scripts/Main.js"></script>
```

I have elm/Main.elm, and I compile it to be next to `app.js` (`elm-make Main.elm --output=../app/scripts/Main.js`). So now, next to app.js we have `Main.js`)

Later, in my controller I'll have

`$scope.elmMain = Elm.Main;`

And in the view:

`<elm-component src="elmMain"></elm-component>`

Note the elm app in my example, is a simple one that looks like this:

```elm
module Main exposing (..)

import Html exposing (text)


main =
    text "Hello - this is Elm embed!"
```

**Comment by samcal** [comment]
Thanks @amitaibu for covering this issue, it slipped through the cracks as I'm not used to maintaining open-source packages! Even though it seems like the workaround is a valid solution, I'll try to take a stab at making the usage a little more friendly.

**Comment by tgelu** [comment]
@amitaibu thank you very much for this :+1:

**Comment by absynce** [comment]
@samcal did you check out my PR (#2) for a solution to this? Please let me know if there are any issues with it.

**Comment by samcal** [comment]
Thanks @absynce! I must have missed it before
